const GET_USERS = 'GET_USERS';
const GET_ALL_LANGUAGE_LIST = 'GET_ALL_LANGUAGE_LIST';
const GET_ALL_QUESTION_LIST = 'GET_ALL_QUESTION_LIST';

const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
const SET_COUNTRY_ITEM = 'SET_COUNTRY_ITEM';
const SET_SEARCH_COUNTRY = 'SET_SEARCH_COUNTRY';
const SET_CHAT_ITEM = 'SET_CHAT_ITEM';
const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY';
const SET_LOGGED_USER = 'SET_LOGGED_USER';

export {
    GET_USERS,
    GET_ALL_LANGUAGE_LIST,
    GET_ALL_QUESTION_LIST,
    
    GET_ALL_COUNTRIES,
    SET_COUNTRY_ITEM,
    SET_SEARCH_COUNTRY,

    SET_CHAT_ITEM,
    SET_CHAT_HISTORY,
    SET_LOGGED_USER
}