const GET_USERS = 'GET_USERS';
const GET_ALL_LANGUAGE_LIST = 'GET_ALL_LANGUAGE_LIST';
const GET_ALL_QUESTION_LIST = 'GET_ALL_QUESTION_LIST';

const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
const SET_COUNTRY_ITEM = 'SET_COUNTRY_ITEM';
const SET_SEARCH_COUNTRY = 'SET_SEARCH_COUNTRY';

export {
    GET_USERS,
    GET_ALL_LANGUAGE_LIST,
    GET_ALL_QUESTION_LIST,
    
    GET_ALL_COUNTRIES,
    SET_COUNTRY_ITEM,
    SET_SEARCH_COUNTRY
}